### PR TITLE
Fix chart height width

### PR DESCRIPTION
**Pull request by maarteNNNN**
Chart size is dynamically readjusted to the container with and height

I get the height and width of the container and readjust the chart element. This is updated on `resize` with an `EventListener`

### CODE REVIEW

**Comment by jondubois** [comment]
I'll test this out. Code looks good. This could be a nice change. Does it still work on mobile and tablet?

**Comment by maarteNNNN** [comment]
On tablet in chrome
image

On mobile in Chrome
image

On mobile Android
image

**Comment by maarteNNNN** [comment]
I tested changing from landscape to portrait on my phone it resizes! ;)

**Review by jondubois — APPROVED** [review]

**Comment by jondubois** [comment]
Very nice!

**Pull request merged**
